version: 2
updates:
- package-ecosystem: npm
  open-pull-requests-limit: 10
  directory: /
  target-branch: develop
  schedule:
    interval: weekly
    day: monday
    time: "07:00"
- package-ecosystem: github-actions
  directory: /
  target-branch: develop
  schedule:
    interval: weekly
    day: monday
    time: "07:00"
