title: mermaid
lang: en
description: Markdownish syntax for generating flowcharts, sequence diagrams, class diagrams, gantt charts and git graphs.

remote_theme: rundocs/jekyll-rtd-theme

mermaid:
  custom: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

copyright:
  since: 2014
  revision: true

edit: true
addons_branch: true

google:
  gtag: UA-153180559-1

sass:
  style: compressed

addons:
  - github
  - i18n
  - analytics

plugins:
  - jemoji

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
