name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Yarn
      run: npm i yarn --global

    - name: Cache Node Modules
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
        
    - name: Cache Cypress
      uses: actions/cache@v1
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}

    - name: Install Packages
      run: |
        yarn config set cache-folder ~/.cache/yarn
        export CYPRESS_CACHE_FOLDER=~/.cache/Cypress
        yarn install --frozen-lockfile
        npx cypress cache path
        npx cypress cache list
        npx cypress verify

    - name: Run Build
      run: yarn build

    - name: Upload Build as Artifact
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist

    - name: Run Unit Tests
      run: |
        yarn test --coverage

    - name: Upload Test Results
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true

    - name: Run E2E Tests
      run: |
        export CYPRESS_CACHE_FOLDER=~/.cache/Cypress
        npx cypress cache path
        npx cypress cache list
        npx cypress install
        yarn e2e
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

    - name: Post Upload Test Results
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
        
    - name: Upload cypress screenshots
      uses: actions/upload-artifact@master
      with:
        name: screenshots
        path: cypress/screenshots
        if: failure()  

    - name: Upload cypress videos
      uses: actions/upload-artifact@master
      with:
        name: videos
        path: cypress/videos
