name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Yarn
      run: npm i yarn --global

    - name: Install Packages
      run: yarn install

    - name: Run Build
      run: yarn build

    - name: Run Unit Tests
      run: |
        yarn test --coverage
        cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

    - name: Run E2E Tests
      run: yarn e2e
