name: E2E

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.2.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Yarn
      run: npm i yarn --global

    - name: Cache Node Modules
      uses: actions/cache@v2.1.5
      with:
        path: .cache
        key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}

    - name: Install Packages
      run: |
        yarn config set cache-folder $GITHUB_WORKSPACE/.cache/yarn
        yarn install --frozen-lockfile
      env:
        CYPRESS_CACHE_FOLDER: .cache/Cypress

    - name: Run Build
      run: yarn build

    # - name: Run e2e Tests
    #   run: |
    #     yarn e2e

    #- name: Upload Test Results
    #  uses: coverallsapp/github-action@v1.0.1
    #  with:
    #    github-token: ${{ secrets.GITHUB_TOKEN }}
    #    parallel: true

    - name: Run E2E Tests
      run: yarn e2e
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        CYPRESS_CACHE_FOLDER: .cache/Cypress

    #- name: Post Upload Test Results
    #  uses: coverallsapp/github-action@master
    #  with:
    #    github-token: ${{ secrets.GITHUB_TOKEN }}
    #    parallel-finished: true