name: Lock closed issue

on: 
  issues:
    types: [closed]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: Dunning-Kruger/lock-issues@v1.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
