name: Validate PR Labeler Configuration
on: [push, pull_request]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Configuration
        uses: Yash-Singh1/pr-labeler-config-validator@releases/v0.0.2
        with:
          configuration-path: .github/pr-labeler.yml
